FROM postgres:latest

#COPY ./data/Employees.sql /docker-entrypoint-initdb.d/
#COPY ./data/France.sql /docker-entrypoint-initdb.d/
#COPY ./data/Store.sql /docker-entrypoint-initdb.d/
#COPY ./data/World.sql /docker-entrypoint-initdb.d/
